apiVersion: v1
kind: Service
metadata:
        name: myweb-svc
spec:
        selector:
                env: production
        type: NodePort
        ports:
                - port: 80
                  nodePort: 32000
